[nodes]
node1 ansible_host=192.168.56.11

[nodes:vars]
ansible_user=roger

[aws]
node-aws ansible_host=18.218.34.247 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/chave-aws-lab.pem

[azure]
node-azure ansible_host=40.123.241.145 ansible_user=rogeradmin ansible_ssh_private_key_file=~/.ssh/azure-lab-key-rsa
