---
- name: Configurar node1 - stack completa
  hosts: all
  become: true
  roles:
    - role: baseline
      tags: [baseline, infra]

    - role: swap
      tags: [swap, infra]

    - role: docker
      tags: [docker, infra]

    - role: firewall
      tags: [firewall, infra]

    - role: node_exporter
      tags: [node_exporter, observability]

    - role: prometheus
      tags: [prometheus, observability]

    - role: loki
      tags: [loki, observability]

    - role: promtail
      tags: [promtail, observability]

    - role: grafana
      tags: [grafana, observability]

    - role: alertmanager
      tags: [alertmanager, observability]

    - role: app-pedidos
      tags: [app-pedidos, app]
