---
- name: Configurar node1 - stack completa
  hosts: all
  become: true
  roles:
    - docker
    - firewall
    - node_exporter
    - prometheus
    - loki
    - promtail
    - grafana
    - alertmanager
    - app-pedidos
    - swap
