---
- name: Instalar firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present
- name: Habilitar e iniciar o firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started
- name: Liberar portas no firewalld
  ansible.posix.firewalld:
    port: '{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  loop: '{{ firewall_ports }}'
