---
- name: Criar diretório de config do Prometheus
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    mode: '0755'

- name: Copiar prometheus.yml para o node1
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
    mode: '0644'

- name: Copiar arquivo de regras de alerta
  ansible.builtin.copy:
    src: alert-rules.yml
    dest: /opt/prometheus/alert-rules.yml
    mode: '0644'

- name: Subir container Prometheus
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    restart_policy: always
    recreate: true
    ports:
      - "9091:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml:ro
